<?
$PERM["index.php"]["6"]="W";
$PERM["index.php"]["9"]="W";
$PERM["services"]["9"]="W";
$PERM["services"]["6"]="W";
$PERM["search"]["9"]="W";
$PERM["search"]["6"]="W";
$PERM["obyavleniya"]["9"]="W";
$PERM["news"]["9"]="W";
$PERM["news"]["6"]="W";
$PERM["contacts"]["9"]="W";
$PERM["contacts"]["6"]="W";
$PERM["company"]["9"]="W";
$PERM["company"]["6"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["9"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["9"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["o-servise"]["9"]="W";
$PERM["bitrix"]["9"]="D";
$PERM["products"]["6"]="W";
$PERM["/"]["*"]="R";
?>